project:
  type: website
  output-dir: docs
  resources:
    - material/**

website:
  title: "Philippa Adolf"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Resources
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks

  page-footer:
    center: "© 2026 Philippa Adolf · University of Vienna"

format:
  html:
    theme: styles.scss
    toc: false
    smooth-scroll: true